# This Github workflow will run the Generate Metadata step of the Ploigos workflow.
name: Generate Metadata

on:
  workflow_call:
    inputs:
      verbose:
        required: false
        type: string
      image:
        required: true
        type: string
      imagePullPolicy:
        required: true
        type: string
      stepRunnerPackageName:
        required: true
        type: string
      venvPath:
        required: true
        type: string
      stepName:
        required: true
        type: string
      stepRunnerConfigDir:
        required: true
        type: string

jobs:
  ci-generate-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ci-generate-metadata
        run: |
          echo 'Generate Metadata'
