name: Setup Stage Gate

on:
  workflow_call:

jobs:
  setup-stage-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup stage gate
        run: |
          echo 'Setup Stage Gate'